
// NZPEPLAB — full research catalogue with rich "Read More" details.
// Drop-in replacement / extension for src/lib/products.ts
// NOTE: All content is for RESEARCH / EDUCATIONAL use only. Prices are placeholder NZD retail — adjust.
 
export type Category =
  | "weight-management"
  | "recovery-repair"
  | "longevity"
  | "performance"
  | "cognitive"
  | "accessories";
 
export const CATEGORIES: { id: Category; name: string; blurb: string }[] = [
  { id: "weight-management", name: "Weight Management", blurb: "Metabolic, appetite & body-composition research." },
  { id: "recovery-repair", name: "Recovery & Repair", blurb: "Tissue, tendon, gut and wound-healing studies." },
  { id: "longevity", name: "Longevity", blurb: "Cellular aging, mitochondria, senescence & skin." },
  { id: "performance", name: "Performance", blurb: "GH axis, endurance, strength & hormonal output." },
  { id: "cognitive", name: "Cognitive & Mood", blurb: "Neurotrophic, anxiolytic, sleep & libido pathways." },
  { id: "accessories", name: "Accessories", blurb: "BAC water, syringes, vials, consumables." },
];
 
// Cross-tags from the brief (a product can sit in one Category but carry several use-tags)
export type Suitability =
  | "longevity" | "wellness" | "health" | "pain"
  | "weight-loss" | "weight-management" | "cognitive"
  | "recovery" | "performance" | "immunity" | "skin"
  | "sexual-health" | "sleep" | "metabolic" | "cardiovascular";
 
// Strength of evidence flag so the UI can label findings honestly
export type Evidence =
  | "approved"        // approved human medicine
  | "clinical"        // human clinical trial data
  | "human-early"     // small / early human data
  | "preclinical"     // animal models
  | "invitro";        // cell / lab only
 
export type PeptideDetails = {
  overview: string;
  mechanism: string;
  suitedFor: Suitability[];
  organsSystems: string[];        // organs / systems protected or acted on
  biomarkers: string[];           // levels / markers reported in studies
  studies: { finding: string; evidence: Evidence }[];
  benefits: string[];
  sideEffects: string[];
  stacking: string[];             // commonly co-studied combinations (slugs or names)
};
 
export type Product = {
  id: string;
  slug: string;
  name: string;
  mg: number | null;
  unit?: "mg" | "iu";
  category: Category;
  price: number;       // NZD (placeholder)
  purity: number;      // percent
  image?: string;      // /products/<slug>.png
  sequence?: string;
  storage?: string;
  description: string;  // short card line
  featured?: boolean;
  details?: PeptideDetails;
};
 
export const RESEARCH_DISCLAIMER =
  "Sold strictly as a laboratory reference material for in-vitro research and analytical use. " +
  "Not a medicine. Not for human or veterinary consumption, diagnosis or treatment. " +
  "Findings below summarise published research (often preclinical) and are educational only.";
 
const STORE_COLD = "Lyophilised powder. Store at -20°C long-term / 2–8°C in use. Reconstitute with bacteriostatic water.";
 
export const PRODUCTS: Product[] = [
  // ─────────────────────────────────────────── WEIGHT MANAGEMENT ───────────────────────────────────────────
  {
    id: "tirzepatide", slug: "tirzepatide", image: "/products/tirzepatide.png", name: "Tirzepatide", mg: 10, unit: "mg",
    category: "weight-management", price: 169, purity: 99, featured: true,
    sequence: "Dual GIP / GLP-1 receptor agonist", storage: STORE_COLD,
    description: "Dual GIP/GLP-1 agonist — landmark metabolic & weight research.",
    details: {
      overview:
        "A dual incretin agonist activating both GIP and GLP-1 receptors. The most studied next-generation metabolic peptide, marketed clinically for type-2 diabetes and obesity.",
      mechanism:
        "Co-agonism of GIP and GLP-1 receptors slows gastric emptying, enhances glucose-dependent insulin secretion, suppresses glucagon and reduces appetite via hypothalamic signalling.",
      suitedFor: ["weight-loss", "weight-management", "metabolic", "health", "cardiovascular"],
      organsSystems: ["Pancreas (β-cell function)", "Hypothalamus (appetite)", "Stomach/GI (gastric emptying)", "Liver (hepatic fat)", "Cardiovascular system"],
      biomarkers: ["HbA1c", "Fasting glucose", "Body weight / waist circumference", "LDL & triglycerides", "Liver fat (MRI-PDFF)"],
      studies: [
        { finding: "SURMOUNT-1: ~20–22% mean body-weight reduction at the 15 mg dose over 72 weeks.", evidence: "clinical" },
        { finding: "SURPASS programme: HbA1c reductions ~2.0–2.4% in type-2 diabetes.", evidence: "clinical" },
        { finding: "Reductions in liver fat and improved lipid profile reported across trials.", evidence: "clinical" },
      ],
      benefits: ["Strong appetite suppression in studies", "Improved glycaemic markers", "Reductions in hepatic fat and lipids"],
      sideEffects: ["Nausea, vomiting, diarrhoea (dose-related)", "Reduced appetite / early satiety", "Rare gallbladder events; injection-site reactions"],
      stacking: ["Cagrilintide", "Semaglutide", "Tesamorelin"],
    },
  },
  {
    id: "retatrutide", slug: "retatrutide", image: "/products/retatrutide.png", name: "Retatrutide", mg: 10, unit: "mg",
    category: "weight-management", price: 219, purity: 99, featured: true,
    sequence: "Triple GLP-1 / GIP / Glucagon agonist", storage: STORE_COLD,
    description: "Triple agonist — among the largest weight reductions reported.",
    details: {
      overview:
        "An investigational 'triple G' agonist hitting GLP-1, GIP and glucagon receptors — adding energy-expenditure effects on top of appetite suppression.",
      mechanism:
        "Glucagon-receptor activation raises energy expenditure and hepatic fat oxidation while GLP-1/GIP arms suppress appetite and improve insulin response.",
      suitedFor: ["weight-loss", "weight-management", "metabolic", "cardiovascular"],
      organsSystems: ["Liver (steatosis)", "Adipose tissue (lipolysis/thermogenesis)", "Pancreas", "Hypothalamus", "Cardiometabolic system"],
      biomarkers: ["Body weight", "Liver fat (MRI-PDFF)", "HbA1c", "Lipids", "Blood pressure"],
      studies: [
        { finding: "Phase-2 obesity trial: up to ~24% mean weight reduction at 48 weeks (12 mg).", evidence: "clinical" },
        { finding: "Near-complete liver-fat clearance reported in many MASLD participants.", evidence: "clinical" },
      ],
      benefits: ["Largest reported trial weight loss to date", "Marked hepatic-fat reduction", "Added thermogenic/energy-expenditure axis"],
      sideEffects: ["GI upset (nausea, diarrhoea)", "Transient heart-rate increase", "Appetite suppression"],
      stacking: ["Cagrilintide"],
    },
  },
  {
    id: "semaglutide", slug: "semaglutide", image: "/products/semaglutide.png", name: "Semaglutide", mg: 5, unit: "mg",
    category: "weight-management", price: 99, purity: 99, featured: true,
    sequence: "GLP-1 receptor agonist", storage: STORE_COLD,
    description: "The reference GLP-1 agonist for metabolic & weight research.",
    details: {
      overview: "A long-acting GLP-1 receptor agonist, the most widely studied incretin therapy for glycaemic control and obesity.",
      mechanism: "GLP-1 receptor agonism increases glucose-dependent insulin secretion, suppresses glucagon, slows gastric emptying and reduces appetite centrally.",
      suitedFor: ["weight-loss", "weight-management", "metabolic", "cardiovascular", "health"],
      organsSystems: ["Pancreas", "Hypothalamus", "Stomach/GI", "Cardiovascular system", "Kidney"],
      biomarkers: ["HbA1c", "Fasting glucose", "Body weight", "LDL/triglycerides", "hs-CRP"],
      studies: [
        { finding: "STEP-1: ~15% mean weight loss at 68 weeks (2.4 mg).", evidence: "clinical" },
        { finding: "SELECT: reduced major cardiovascular events in overweight/obese adults.", evidence: "clinical" },
      ],
      benefits: ["Robust appetite control", "Cardiovascular risk reduction in trials", "Improved glycaemic markers"],
      sideEffects: ["Nausea, constipation/diarrhoea", "Early satiety", "Rare pancreatitis/gallbladder events"],
      stacking: ["Cagrilintide", "Tirzepatide"],
    },
  },
  {
    id: "cagrilintide", slug: "cagrilintide", image: "/products/cagrilintide.png", name: "Cagrilintide", mg: 5, unit: "mg",
    category: "weight-management", price: 119, purity: 99,
    sequence: "Long-acting amylin analog", storage: STORE_COLD,
    description: "Amylin analog — appetite & satiety research, pairs with GLP-1s.",
    details: {
      overview: "A long-acting amylin receptor agonist studied for satiety and weight, frequently combined with semaglutide (CagriSema).",
      mechanism: "Amylin-receptor agonism promotes satiety, slows gastric emptying and reduces food intake through hindbrain and hypothalamic circuits, complementary to GLP-1.",
      suitedFor: ["weight-loss", "weight-management", "metabolic"],
      organsSystems: ["Hypothalamus/hindbrain (satiety)", "Stomach/GI", "Pancreas (glucagon modulation)"],
      biomarkers: ["Body weight", "Caloric intake", "HbA1c (in combinations)"],
      studies: [
        { finding: "CagriSema phase-2/3: combined ~15–22% weight loss vs either agent alone.", evidence: "clinical" },
      ],
      benefits: ["Additive appetite suppression with GLP-1s", "Slower gastric emptying", "Improved satiety signalling"],
      sideEffects: ["Nausea, GI upset", "Injection-site reactions"],
      stacking: ["Semaglutide", "Tirzepatide", "Retatrutide"],
    },
  },
  {
    id: "cagri-sema", slug: "cagrilintide-semaglutide", image: "/products/cagrilintide-semaglutide.png", name: "Cagrilintide + Semaglutide Blend", mg: 5, unit: "mg",
    category: "weight-management", price: 149, purity: 99,
    sequence: "Amylin analog + GLP-1 (5 mg + 5 mg)", storage: STORE_COLD,
    description: "Combined amylin + GLP-1 satiety research blend.",
    details: {
      overview: "Co-formulated amylin analog and GLP-1 agonist (the 'CagriSema' combination) studied for additive appetite and weight effects.",
      mechanism: "Pairs amylin-driven satiety with GLP-1 appetite/glycaemic effects for complementary metabolic signalling.",
      suitedFor: ["weight-loss", "weight-management", "metabolic"],
      organsSystems: ["Hypothalamus/hindbrain", "Stomach/GI", "Pancreas"],
      biomarkers: ["Body weight", "HbA1c", "Caloric intake"],
      studies: [{ finding: "Combination produced greater weight loss than either component in trials.", evidence: "clinical" }],
      benefits: ["Dual satiety pathways", "Strong appetite control in studies"],
      sideEffects: ["Nausea/GI upset", "Early satiety"],
      stacking: ["Tirzepatide"],
    },
  },
  {
    id: "survodutide", slug: "survodutide", image: "/products/survodutide.png", name: "Survodutide", mg: 5, unit: "mg",
    category: "weight-management", price: 159, purity: 99,
    sequence: "GLP-1 / Glucagon dual agonist", storage: STORE_COLD,
    description: "GLP-1/glucagon dual agonist — weight & liver (MASH) research.",
    details: {
      overview: "A dual GLP-1/glucagon receptor agonist studied for obesity and metabolic-associated steatohepatitis (MASH).",
      mechanism: "GLP-1 appetite suppression plus glucagon-driven energy expenditure and hepatic fat oxidation.",
      suitedFor: ["weight-loss", "weight-management", "metabolic"],
      organsSystems: ["Liver (steatohepatitis)", "Adipose tissue", "Hypothalamus", "Pancreas"],
      biomarkers: ["Body weight", "Liver fat & fibrosis markers", "ALT/AST", "HbA1c"],
      studies: [
        { finding: "Phase-2 obesity: ~19% mean weight loss at 46 weeks.", evidence: "clinical" },
        { finding: "Phase-2 MASH: high rate of histological improvement vs placebo.", evidence: "clinical" },
      ],
      benefits: ["Weight loss plus liver-directed effects", "Energy-expenditure component"],
      sideEffects: ["GI upset", "Appetite suppression"],
      stacking: ["Cagrilintide"],
    },
  },
  {
    id: "aod-9604", slug: "aod-9604", image: "/products/aod-9604.png", name: "AOD-9604", mg: 5, unit: "mg",
    category: "weight-management", price: 59, purity: 99,
    sequence: "hGH fragment 176-191 analog", storage: STORE_COLD,
    description: "GH-fragment analog studied for lipolysis without GH effects.",
    details: {
      overview: "A modified C-terminal fragment of growth hormone studied for fat metabolism without the glucose effects of full GH.",
      mechanism: "Stimulates lipolysis and inhibits lipogenesis in adipose tissue, reportedly via β3-adrenergic-like signalling, without raising IGF-1 or blood glucose.",
      suitedFor: ["weight-loss", "weight-management", "metabolic"],
      organsSystems: ["Adipose tissue", "Cartilage (repair research)"],
      biomarkers: ["Body fat %", "Lipid oxidation markers"],
      studies: [
        { finding: "Preclinical: increased fat oxidation and reduced adiposity in rodent models.", evidence: "preclinical" },
        { finding: "Early human studies showed good tolerability; weight effects modest.", evidence: "human-early" },
      ],
      benefits: ["Targets adipose lipolysis", "No reported rise in IGF-1/glucose"],
      sideEffects: ["Generally well tolerated in studies", "Injection-site reactions"],
      stacking: ["CJC-1295 No DAC", "Ipamorelin", "HGH Fragment 176-191"],
    },
  },
  {
    id: "hgh-frag-176-191", slug: "hgh-fragment-176-191", image: "/products/hgh-fragment-176-191.png", name: "HGH Fragment 176-191", mg: 5, unit: "mg",
    category: "weight-management", price: 55, purity: 99,
    sequence: "GH C-terminal fragment (176-191)", storage: STORE_COLD,
    description: "GH lipolytic fragment — adipose-tissue fat metabolism research.",
    details: {
      overview: "The lipolytic C-terminal fragment of growth hormone, studied for fat-burning effects isolated from GH's growth signalling.",
      mechanism: "Mimics GH's lipolytic action on adipocytes while reportedly avoiding effects on IGF-1, insulin sensitivity or growth.",
      suitedFor: ["weight-loss", "weight-management", "metabolic"],
      organsSystems: ["Adipose tissue"],
      biomarkers: ["Body fat %", "Free fatty acids"],
      studies: [{ finding: "Preclinical lipolysis and reduced fat mass in animal models.", evidence: "preclinical" }],
      benefits: ["Selective lipolytic action in studies"],
      sideEffects: ["Generally well tolerated", "Injection-site reactions"],
      stacking: ["AOD-9604", "CJC-1295 No DAC", "Ipamorelin"],
    },
  },
  {
    id: "5-amino-1mq", slug: "5-amino-1mq", image: "/products/5-amino-1mq.png", name: "5-Amino-1MQ", mg: 50, unit: "mg",
    category: "weight-management", price: 75, purity: 99,
    sequence: "NNMT small-molecule inhibitor", storage: STORE_COLD,
    description: "NNMT inhibitor — adipocyte metabolism & NAD+ research.",
    details: {
      overview: "A small-molecule inhibitor of nicotinamide N-methyltransferase (NNMT) studied for adipocyte energy metabolism and obesity.",
      mechanism: "Inhibiting NNMT raises cellular NAD+ and SAM levels, increasing adipocyte energy expenditure and limiting fat-cell expansion in models.",
      suitedFor: ["weight-loss", "weight-management", "metabolic", "longevity"],
      organsSystems: ["Adipose tissue", "Skeletal muscle (metabolic)"],
      biomarkers: ["NAD+ levels", "Adipocyte size", "Body fat %"],
      studies: [{ finding: "Preclinical: reduced fat mass and improved metabolic markers in obese mice.", evidence: "preclinical" }],
      benefits: ["Supports adipocyte NAD+ in studies", "Oral-active small molecule"],
      sideEffects: ["Limited human safety data"],
      stacking: ["NAD+", "MOTS-C"],
    },
  },
  {
    id: "adipotide", slug: "adipotide", image: "/products/adipotide.png", name: "Adipotide (FTPP)", mg: 10, unit: "mg",
    category: "weight-management", price: 95, purity: 98,
    sequence: "Pro-apoptotic targeting peptide", storage: STORE_COLD,
    description: "Pro-apoptotic peptide targeting fat-tissue vasculature (research).",
    details: {
      overview: "An experimental targeting peptide studied for selectively reducing white adipose tissue by acting on its blood supply.",
      mechanism: "Targets prohibitin on adipose-tissue vasculature and triggers apoptosis of the vessels feeding fat depots, causing fat loss in models.",
      suitedFor: ["weight-loss", "weight-management"],
      organsSystems: ["Adipose tissue vasculature", "Kidney (monitored for effects)"],
      biomarkers: ["Body weight", "Fat mass"],
      studies: [{ finding: "Preclinical: marked weight/fat loss in obese primates; renal effects observed.", evidence: "preclinical" }],
      benefits: ["Targets fat vasculature in studies"],
      sideEffects: ["Renal effects reported in animals", "Limited/early data — research only"],
      stacking: [],
    },
  },
  {
    id: "tesamorelin", slug: "tesamorelin", image: "/products/tesamorelin.png", name: "Tesamorelin", mg: 5, unit: "mg",
    category: "weight-management", price: 99, purity: 99,
    sequence: "GHRH analog", storage: STORE_COLD,
    description: "GHRH analog — visceral-fat & GH-axis research (approved drug).",
    details: {
      overview: "A stabilised growth-hormone-releasing hormone analog, approved clinically to reduce visceral adipose tissue in HIV-lipodystrophy.",
      mechanism: "Stimulates pituitary GH release in a physiological, pulsatile manner, raising IGF-1 and preferentially reducing visceral fat.",
      suitedFor: ["weight-management", "performance", "metabolic", "longevity"],
      organsSystems: ["Pituitary (GH axis)", "Visceral adipose tissue", "Liver (IGF-1)"],
      biomarkers: ["IGF-1", "Visceral adipose tissue (CT)", "Triglycerides"],
      studies: [{ finding: "Clinical: ~15–18% reduction in visceral adipose tissue.", evidence: "approved" }],
      benefits: ["Targets visceral fat in trials", "Physiological GH release"],
      sideEffects: ["Joint pain/oedema", "Hyperglycaemia risk", "Injection-site reactions"],
      stacking: ["Ipamorelin", "CJC-1295 No DAC"],
    },
  },
 
  // ─────────────────────────────────────────── RECOVERY & REPAIR ───────────────────────────────────────────
  {
    id: "bpc-157", slug: "bpc-157", image: "/products/bpc-157.png", name: "BPC-157", mg: 5, unit: "mg",
    category: "recovery-repair", price: 49, purity: 99, featured: true,
    sequence: "Body Protection Compound (15-aa)", storage: STORE_COLD,
    description: "Gastric pentadecapeptide — tendon, gut & vascular repair research.",
    details: {
      overview: "A synthetic pentadecapeptide derived from a gastric protein, among the most studied 'healing' peptides in preclinical literature.",
      mechanism: "Up-regulates VEGFR2–Akt–eNOS signalling to promote angiogenesis (new blood vessels), modulates the nitric-oxide system, growth-factor expression and the gut–brain axis.",
      suitedFor: ["recovery", "pain", "health", "wellness"],
      organsSystems: ["Tendons & ligaments", "Gastrointestinal tract (stomach/intestine)", "Vascular endothelium", "Liver", "Peripheral nerves", "Musculoskeletal tissue"],
      biomarkers: ["VEGFR2 expression", "Nitric-oxide pathway markers", "Collagen organisation in healing tissue"],
      studies: [
        { finding: "Accelerated tendon-to-bone and ligament healing in rodent models.", evidence: "preclinical" },
        { finding: "Protected gastric/intestinal mucosa and reduced NSAID-induced lesions in animals.", evidence: "preclinical" },
        { finding: "Promoted angiogenesis and nerve recovery in injury models.", evidence: "preclinical" },
      ],
      benefits: ["Studied for tendon/ligament repair", "Gut-protective in models", "Angiogenic / vascular support"],
      sideEffects: ["No formal human safety profile", "Mild injection-site reactions reported anecdotally"],
      stacking: ["TB-500", "KPV", "GHK-Cu"],
    },
  },
  {
    id: "tb-500", slug: "tb-500", image: "/products/tb-500.png", name: "TB-500 (Thymosin β4)", mg: 5, unit: "mg",
    category: "recovery-repair", price: 59, purity: 99, featured: true,
    sequence: "Thymosin Beta-4 fragment", storage: STORE_COLD,
    description: "Actin-regulating peptide — cell migration & cardiac repair research.",
    details: {
      overview: "A synthetic fragment of Thymosin Beta-4, a naturally occurring actin-sequestering peptide central to cell migration and wound repair.",
      mechanism: "Regulates actin polymerisation, promoting cell migration, angiogenesis and down-regulating inflammation and fibrosis in injured tissue.",
      suitedFor: ["recovery", "pain", "cardiovascular", "wellness"],
      organsSystems: ["Heart (myocardium)", "Skeletal muscle & tendon", "Cornea/eye", "Skin (wounds)", "Blood vessels"],
      biomarkers: ["Actin dynamics", "Angiogenic markers", "Inflammatory cytokines"],
      studies: [
        { finding: "Promoted cardiomyocyte survival and repair after ischaemia in animal models.", evidence: "preclinical" },
        { finding: "Accelerated corneal and dermal wound healing.", evidence: "preclinical" },
      ],
      benefits: ["Studied for soft-tissue and cardiac repair", "Anti-fibrotic in models", "Supports cell migration"],
      sideEffects: ["No formal human safety profile", "Injection-site reactions reported anecdotally"],
      stacking: ["BPC-157", "GHK-Cu"],
    },
  },
  {
    id: "blend-bpc-tb", slug: "bpc-157-tb-500-blend", image: "/products/bpc-157-tb-500-blend.png", name: "BPC-157 + TB-500 Blend", mg: 10, unit: "mg",
    category: "recovery-repair", price: 99, purity: 99, featured: true,
    sequence: "BPC-157 + TB-500 (e.g. 5+5 / 10+10)", storage: STORE_COLD,
    description: "The classic recovery stack — combined repair pathways.",
    details: {
      overview: "Combines BPC-157's angiogenic, gut- and tendon-directed action with TB-500's actin/cell-migration effects — the most common recovery research pairing.",
      mechanism: "Complementary: BPC-157 drives VEGFR2-mediated angiogenesis and tissue protection; TB-500 supports cell migration and anti-fibrotic repair.",
      suitedFor: ["recovery", "pain", "wellness", "cardiovascular"],
      organsSystems: ["Tendons/ligaments", "GI tract", "Heart", "Skeletal muscle", "Vasculature"],
      biomarkers: ["VEGFR2", "Actin dynamics", "Collagen organisation"],
      studies: [{ finding: "Components individually show repair effects in preclinical models; combined use is research-driven.", evidence: "preclinical" }],
      benefits: ["Two complementary repair pathways", "Popular soft-tissue research stack"],
      sideEffects: ["No formal human safety profile"],
      stacking: ["GHK-Cu", "KPV"],
    },
  },
  {
    id: "klow", slug: "klow-blend", image: "/products/klow-blend.png", name: "KLOW Blend (BPC+TB+GHK-Cu+KPV)", mg: 80, unit: "mg",
    category: "recovery-repair", price: 199, purity: 99,
    sequence: "BPC-157 + TB-500 + GHK-Cu + KPV", storage: STORE_COLD,
    description: "Four-way repair / anti-inflammatory research blend.",
    details: {
      overview: "A four-peptide research blend combining repair (BPC-157, TB-500), regenerative copper-peptide (GHK-Cu) and anti-inflammatory (KPV) actions.",
      mechanism: "Layers angiogenesis, cell migration, collagen/gene-expression remodelling and gut/systemic anti-inflammatory signalling.",
      suitedFor: ["recovery", "pain", "skin", "wellness", "immunity"],
      organsSystems: ["Connective tissue", "GI tract", "Skin", "Vasculature"],
      biomarkers: ["VEGFR2", "Collagen synthesis", "Inflammatory cytokines (TNF-α/NF-κB)"],
      studies: [{ finding: "Each component has independent preclinical support; blend is research-oriented.", evidence: "preclinical" }],
      benefits: ["Broad repair + anti-inflammatory coverage"],
      sideEffects: ["No formal human safety profile"],
      stacking: [],
    },
  },
  {
    id: "kpv", slug: "kpv", image: "/products/kpv.png", name: "KPV", mg: 10, unit: "mg",
    category: "recovery-repair", price: 45, purity: 99,
    sequence: "α-MSH C-terminal tripeptide (Lys-Pro-Val)", storage: STORE_COLD,
    description: "α-MSH fragment — gut & systemic anti-inflammatory research.",
    details: {
      overview: "The C-terminal tripeptide of α-MSH, studied for potent anti-inflammatory action, particularly in the gut.",
      mechanism: "Enters cells and inhibits NF-κB and pro-inflammatory cytokine signalling without the pigmentation effects of full α-MSH.",
      suitedFor: ["recovery", "immunity", "health", "pain"],
      organsSystems: ["Gastrointestinal tract (colon)", "Skin", "Immune cells"],
      biomarkers: ["TNF-α", "IL-1β / IL-6", "NF-κB activity"],
      studies: [{ finding: "Reduced colitis severity and inflammatory cytokines in animal models.", evidence: "preclinical" }],
      benefits: ["Gut anti-inflammatory in studies", "Non-pigmenting α-MSH effects"],
      sideEffects: ["Limited human safety data"],
      stacking: ["BPC-157", "TB-500", "LL-37"],
    },
  },
  {
    id: "ll-37", slug: "ll-37", image: "/products/ll-37.png", name: "LL-37", mg: 5, unit: "mg",
    category: "recovery-repair", price: 79, purity: 98,
    sequence: "Cathelicidin antimicrobial peptide", storage: STORE_COLD,
    description: "Cathelicidin — antimicrobial, wound & immune research.",
    details: {
      overview: "The only human cathelicidin antimicrobial peptide, studied for innate immunity, wound healing and biofilm disruption.",
      mechanism: "Disrupts microbial membranes, neutralises endotoxin, and modulates immune-cell recruitment and angiogenesis in wounds.",
      suitedFor: ["immunity", "recovery", "health"],
      organsSystems: ["Skin (wounds)", "Respiratory tract", "Immune system"],
      biomarkers: ["Bacterial load", "Wound-closure rate", "Inflammatory cytokines"],
      studies: [{ finding: "Antimicrobial and pro-healing effects in infection/wound models.", evidence: "preclinical" }],
      benefits: ["Broad antimicrobial action in studies", "Immune-modulating"],
      sideEffects: ["Can be pro-inflammatory at high levels", "Limited human safety data"],
      stacking: ["KPV", "BPC-157"],
    },
  },
  {
    id: "ara-290", slug: "ara-290", image: "/products/ara-290.png", name: "ARA-290 (Cibinetide)", mg: 10, unit: "mg",
    category: "recovery-repair", price: 89, purity: 99,
    sequence: "Erythropoietin-derived 11-aa peptide", storage: STORE_COLD,
    description: "Tissue-protective EPO peptide — neuropathy & inflammation research.",
    details: {
      overview: "An 11-amino-acid peptide derived from erythropoietin that activates tissue protection without erythropoietin's effect on red blood cells.",
      mechanism: "Activates the innate repair receptor (EPOR/β-common receptor) to reduce inflammation and protect nerves and tissue.",
      suitedFor: ["pain", "recovery", "health", "wellness"],
      organsSystems: ["Peripheral nerves (small-fibre)", "Pancreas (islets)", "Eye", "Vasculature"],
      biomarkers: ["Neuropathic pain scores", "Corneal nerve fibre density", "Inflammatory markers"],
      studies: [
        { finding: "Improved small-fibre neuropathy measures and pain in sarcoidosis/diabetes trials.", evidence: "human-early" },
        { finding: "Tissue-protective, anti-inflammatory effects without raising haematocrit.", evidence: "preclinical" },
      ],
      benefits: ["Neuropathic-pain research", "Tissue protection without RBC effects"],
      sideEffects: ["Generally well tolerated in early trials"],
      stacking: ["BPC-157"],
    },
  },
  {
    id: "dermorphin", slug: "dermorphin", image: "/products/dermorphin.png", name: "Dermorphin", mg: 5, unit: "mg",
    category: "recovery-repair", price: 89, purity: 98,
    sequence: "μ-opioid heptapeptide", storage: STORE_COLD,
    description: "Potent μ-opioid peptide — analgesia research only.",
    details: {
      overview: "A naturally occurring opioid heptapeptide (from amphibian skin) studied as an extremely potent μ-opioid receptor agonist.",
      mechanism: "Selective μ-opioid receptor agonism producing analgesia far more potent than morphine in models.",
      suitedFor: ["pain"],
      organsSystems: ["Central & peripheral nervous system (opioid receptors)"],
      biomarkers: ["Nociception thresholds"],
      studies: [{ finding: "Potent analgesia in animal models.", evidence: "preclinical" }],
      benefits: ["Analgesia research reference"],
      sideEffects: ["Opioid-class risks: respiratory depression, dependence — strictly research only"],
      stacking: [],
    },
  },
  {
    id: "vip", slug: "vip", image: "/products/vip.png", name: "VIP (Vasoactive Intestinal Peptide)", mg: 5, unit: "mg",
    category: "recovery-repair", price: 95, purity: 98,
    sequence: "28-aa neuropeptide", storage: STORE_COLD,
    description: "Anti-inflammatory neuropeptide — respiratory & immune research.",
    details: {
      overview: "A 28-amino-acid neuropeptide with broad anti-inflammatory and vasodilatory roles, studied in respiratory and immune contexts.",
      mechanism: "Activates VPAC receptors, raising cAMP to relax smooth muscle, dampen inflammatory cytokines and support immune balance.",
      suitedFor: ["immunity", "recovery", "health", "wellness"],
      organsSystems: ["Lungs/airways", "Gastrointestinal tract", "Immune system", "Vasculature"],
      biomarkers: ["Inflammatory cytokines", "Pulmonary pressures (in PAH research)"],
      studies: [{ finding: "Anti-inflammatory and bronchodilatory effects in respiratory models/early studies.", evidence: "human-early" }],
      benefits: ["Anti-inflammatory research", "Airway/immune modulation"],
      sideEffects: ["Flushing, low blood pressure possible", "Limited human safety data"],
      stacking: [],
    },
  },
 
  // ─────────────────────────────────────────── LONGEVITY ───────────────────────────────────────────
  {
    id: "epithalon", slug: "epithalon", image: "/products/epithalon.png", name: "Epithalon (Epitalon)", mg: 10, unit: "mg",
    category: "longevity", price: 45, purity: 99, featured: true,
    sequence: "Tetrapeptide Ala-Glu-Asp-Gly", storage: STORE_COLD,
    description: "Telomerase & pineal/circadian peptide — aging research.",
    details: {
      overview: "A synthetic tetrapeptide studied for telomerase activation, pineal-gland function and circadian/melatonin regulation in aging models.",
      mechanism: "Reported to up-regulate telomerase, support melatonin rhythm and modulate gene expression linked to aging.",
      suitedFor: ["longevity", "wellness", "sleep", "health"],
      organsSystems: ["Pineal gland (melatonin)", "Telomeres/chromatin", "Immune system", "Retina"],
      biomarkers: ["Telomerase activity", "Melatonin rhythm", "Cortisol/melatonin balance"],
      studies: [
        { finding: "Activated telomerase and extended replicative capacity in human cell cultures.", evidence: "invitro" },
        { finding: "Improved survival/lifespan markers in some rodent studies.", evidence: "preclinical" },
      ],
      benefits: ["Telomere/aging research", "Circadian & melatonin support in studies"],
      sideEffects: ["Limited human safety data"],
      stacking: ["GHK-Cu", "NAD+", "Thymalin"],
    },
  },
  {
    id: "ghk-cu", slug: "ghk-cu", image: "/products/ghk-cu.png", name: "GHK-Cu", mg: 50, unit: "mg",
    category: "longevity", price: 65, purity: 99, featured: true,
    sequence: "Copper tripeptide Gly-His-Lys-Cu", storage: STORE_COLD,
    description: "Copper peptide — skin, collagen & gene-expression research.",
    details: {
      overview: "A naturally occurring copper-binding tripeptide that declines with age, heavily studied for skin remodelling and tissue regeneration.",
      mechanism: "Delivers copper and resets gene expression toward repair — stimulating collagen/elastin, antioxidant defence and angiogenesis.",
      suitedFor: ["longevity", "skin", "recovery", "wellness"],
      organsSystems: ["Skin (dermis)", "Hair follicles", "Connective tissue", "Vasculature"],
      biomarkers: ["Collagen/elastin synthesis", "Antioxidant enzyme expression", "Gene-expression resets (thousands of genes in studies)"],
      studies: [
        { finding: "Stimulated collagen and improved skin firmness/wrinkles in human skin studies.", evidence: "human-early" },
        { finding: "Reset large numbers of genes toward a younger profile in cell studies.", evidence: "invitro" },
      ],
      benefits: ["Skin & collagen research", "Wound-healing and antioxidant support"],
      sideEffects: ["Topical generally well tolerated", "Limited injectable human data"],
      stacking: ["BPC-157", "TB-500", "Epithalon"],
    },
  },
  {
    id: "nad-plus", slug: "nad-plus", image: "/products/nad-plus.png", name: "NAD+", mg: 500, unit: "mg",
    category: "longevity", price: 89, purity: 99, featured: true,
    sequence: "Nicotinamide adenine dinucleotide", storage: STORE_COLD,
    description: "Core metabolic coenzyme — energy & longevity research.",
    details: {
      overview: "A central coenzyme in cellular energy metabolism and DNA repair that declines with age — a cornerstone of longevity research.",
      mechanism: "Fuels mitochondrial ATP production and acts as a substrate for sirtuins and PARPs governing DNA repair and metabolic signalling.",
      suitedFor: ["longevity", "wellness", "metabolic", "cognitive", "health"],
      organsSystems: ["Mitochondria (all tissues)", "Brain", "Liver", "Skeletal muscle"],
      biomarkers: ["Tissue NAD+ levels", "Sirtuin activity", "Mitochondrial function"],
      studies: [
        { finding: "NAD+ precursors raised blood NAD+ and improved some metabolic markers in human trials.", evidence: "clinical" },
        { finding: "Mitochondrial and lifespan benefits in animal/model studies.", evidence: "preclinical" },
      ],
      benefits: ["Cellular-energy & DNA-repair research", "Supports sirtuin pathways"],
      sideEffects: ["Flushing/nausea with rapid administration"],
      stacking: ["5-Amino-1MQ", "MOTS-C", "SS-31"],
    },
  },
  {
    id: "ss-31", slug: "ss-31", image: "/products/ss-31.png", name: "SS-31 (Elamipretide)", mg: 10, unit: "mg",
    category: "longevity", price: 129, purity: 99,
    sequence: "Mitochondria-targeting tetrapeptide", storage: STORE_COLD,
    description: "Cardiolipin-targeting peptide — mitochondrial function research.",
    details: {
      overview: "A mitochondria-targeted tetrapeptide that binds cardiolipin on the inner membrane, studied for diseases of mitochondrial dysfunction.",
      mechanism: "Stabilises cardiolipin and the electron-transport chain, improving ATP output and reducing reactive oxygen species.",
      suitedFor: ["longevity", "performance", "cardiovascular", "wellness"],
      organsSystems: ["Heart", "Skeletal muscle", "Kidney", "Eye (retina)", "Brain"],
      biomarkers: ["Mitochondrial ATP production", "6-minute walk distance (trials)", "ROS markers"],
      studies: [
        { finding: "Improved skeletal-muscle bioenergetics and function in mitochondrial-myopathy trials.", evidence: "clinical" },
        { finding: "Cardioprotective and renal-protective effects in preclinical models.", evidence: "preclinical" },
      ],
      benefits: ["Mitochondrial-function research", "Cardiac/muscle bioenergetics"],
      sideEffects: ["Injection-site reactions in trials"],
      stacking: ["NAD+", "MOTS-C"],
    },
  },
  {
    id: "foxo4-dri", slug: "foxo4-dri", image: "/products/foxo4-dri.png", name: "FOXO4-DRI", mg: 10, unit: "mg",
    category: "longevity", price: 149, purity: 98,
    sequence: "FOXO4 D-retro-inverso senolytic peptide", storage: STORE_COLD,
    description: "Senolytic peptide — clearing senescent cells (research).",
    details: {
      overview: "A D-retro-inverso peptide studied as a senolytic — selectively removing senescent ('zombie') cells that accumulate with age.",
      mechanism: "Disrupts the FOXO4–p53 interaction in senescent cells, releasing p53 to trigger their apoptosis while sparing healthy cells.",
      suitedFor: ["longevity", "wellness"],
      organsSystems: ["Kidney", "Skin", "Liver", "Systemic (senescent-cell burden)"],
      biomarkers: ["Senescence markers (p16, SA-β-gal)", "SASP cytokines"],
      studies: [{ finding: "Cleared senescent cells and restored fitness/fur/renal markers in aged mice.", evidence: "preclinical" }],
      benefits: ["Senolytic / cellular-aging research"],
      sideEffects: ["Limited human safety data — research only"],
      stacking: ["NAD+", "Epithalon"],
    },
  },
  {
    id: "thymalin", slug: "thymalin", image: "/products/thymalin.png", name: "Thymalin", mg: 10, unit: "mg",
    category: "longevity", price: 69, purity: 99,
    sequence: "Thymus peptide complex", storage: STORE_COLD,
    description: "Thymic peptide — immune-aging & restoration research.",
    details: {
      overview: "A thymus-derived peptide preparation studied for restoring immune balance in aging.",
      mechanism: "Modulates T-cell differentiation and immune signalling, supporting a more youthful immune profile in studies.",
      suitedFor: ["longevity", "immunity", "wellness", "health"],
      organsSystems: ["Thymus", "Immune system (T-cells)"],
      biomarkers: ["T-cell subsets (CD4/CD8)", "Inflammatory markers"],
      studies: [{ finding: "Improved immune indices and reported survival benefit in elderly cohorts (older studies).", evidence: "human-early" }],
      benefits: ["Immune-aging research", "Immune restoration in studies"],
      sideEffects: ["Limited modern human data"],
      stacking: ["Thymosin Alpha-1", "Epithalon"],
    },
  },
  {
    id: "thymosin-alpha-1", slug: "thymosin-alpha-1", image: "/products/thymosin-alpha-1.png", name: "Thymosin Alpha-1", mg: 5, unit: "mg",
    category: "longevity", price: 99, purity: 99,
    sequence: "28-aa thymic peptide", storage: STORE_COLD,
    description: "Immune-modulating thymic peptide — infection & immunity research.",
    details: {
      overview: "A thymus-derived 28-amino-acid peptide (clinically used in some countries as Zadaxin) studied for immune modulation in infection and immune dysfunction.",
      mechanism: "Enhances T-cell maturation, dendritic-cell function and Toll-like-receptor signalling, balancing immune responses.",
      suitedFor: ["immunity", "longevity", "health", "wellness"],
      organsSystems: ["Immune system (T-cells, dendritic cells)", "Liver (hepatitis research)"],
      biomarkers: ["T-cell counts", "Antibody/vaccine response", "Inflammatory cytokines"],
      studies: [
        { finding: "Improved outcomes/immune markers in chronic hepatitis and sepsis trials.", evidence: "clinical" },
      ],
      benefits: ["Immune-modulation research", "Studied in chronic infection"],
      sideEffects: ["Generally well tolerated; injection-site reactions"],
      stacking: ["Thymalin", "LL-37"],
    },
  },
  {
    id: "glutathione", slug: "glutathione", image: "/products/glutathione.png", name: "Glutathione", mg: 600, unit: "mg",
    category: "longevity", price: 49, purity: 99,
    sequence: "Tripeptide γ-Glu-Cys-Gly", storage: STORE_COLD,
    description: "Master antioxidant tripeptide — detox & oxidative-stress research.",
    details: {
      overview: "The body's principal intracellular antioxidant tripeptide, studied for oxidative-stress, detoxification and skin research.",
      mechanism: "Neutralises reactive oxygen species, regenerates other antioxidants and supports phase-II liver detoxification.",
      suitedFor: ["longevity", "wellness", "health", "skin"],
      organsSystems: ["Liver", "Skin", "Lungs", "Systemic (redox balance)"],
      biomarkers: ["Reduced/oxidised glutathione ratio", "Oxidative-stress markers (MDA)"],
      studies: [{ finding: "Raised glutathione status and reduced oxidative markers in human studies.", evidence: "clinical" }],
      benefits: ["Antioxidant & detox research", "Skin-tone research (melanin pathway)"],
      sideEffects: ["Generally well tolerated"],
      stacking: ["NAD+", "GHK-Cu"],
    },
  },
  {
    id: "matrixyl-3000", slug: "matrixyl-3000", image: "/products/matrixyl-3000.png", name: "Matrixyl 3000", mg: 50, unit: "mg",
    category: "longevity", price: 39, purity: 98,
    sequence: "Palmitoyl peptides (Pal-GHK + Pal-GQPR)", storage: STORE_COLD,
    description: "Cosmetic matrikine — collagen & anti-wrinkle research.",
    details: {
      overview: "A cosmetic peptide complex of matrikines studied for stimulating skin matrix renewal and reducing wrinkle depth.",
      mechanism: "Signals fibroblasts to increase collagen, elastin and glycosaminoglycan synthesis, mimicking matrix-repair messengers.",
      suitedFor: ["skin", "longevity"],
      organsSystems: ["Skin (dermal matrix)"],
      biomarkers: ["Collagen-I synthesis", "Wrinkle depth"],
      studies: [{ finding: "Reduced wrinkle volume and improved skin density in cosmetic studies.", evidence: "human-early" }],
      benefits: ["Topical anti-aging skin research"],
      sideEffects: ["Topical use; well tolerated"],
      stacking: ["GHK-Cu", "SNAP-8", "Oligopeptide-24"],
    },
  },
  {
    id: "snap-8", slug: "snap-8", image: "/products/snap-8.png", name: "SNAP-8 (Acetyl Octapeptide-3)", mg: 10, unit: "mg",
    category: "longevity", price: 39, purity: 98,
    sequence: "Acetyl octapeptide-3", storage: STORE_COLD,
    description: "Topical 'expression-line' peptide — anti-wrinkle research.",
    details: {
      overview: "A cosmetic octapeptide studied for softening expression lines by reducing muscle-contraction signalling at the skin level.",
      mechanism: "Competes with SNAP-25 in the SNARE complex, modestly reducing catecholamine/acetylcholine release and muscle contraction.",
      suitedFor: ["skin"],
      organsSystems: ["Skin (facial expression lines)"],
      biomarkers: ["Wrinkle depth/length"],
      studies: [{ finding: "Reduced wrinkle depth in topical cosmetic studies.", evidence: "human-early" }],
      benefits: ["Topical expression-line research"],
      sideEffects: ["Topical; well tolerated"],
      stacking: ["Matrixyl 3000", "Oligopeptide-24"],
    },
  },
  {
    id: "oligopeptide-24", slug: "oligopeptide-24", image: "/products/oligopeptide-24.png", name: "Oligopeptide-24", mg: 5, unit: "mg",
    category: "longevity", price: 49, purity: 98,
    sequence: "Recombinant growth-factor-like peptide", storage: STORE_COLD,
    description: "Skin growth-factor-like peptide — regeneration research.",
    details: {
      overview: "A bioengineered peptide studied for skin regeneration and barrier support, often in cosmetic formulations.",
      mechanism: "Acts on growth-factor-like pathways to support fibroblast activity, antioxidant defence and skin renewal.",
      suitedFor: ["skin", "longevity"],
      organsSystems: ["Skin"],
      biomarkers: ["Skin elasticity/hydration", "Collagen markers"],
      studies: [{ finding: "Improved skin texture/elasticity in cosmetic studies.", evidence: "human-early" }],
      benefits: ["Skin-renewal research"],
      sideEffects: ["Topical; well tolerated"],
      stacking: ["GHK-Cu", "Matrixyl 3000"],
    },
  },
 
  // ─────────────────────────────────────────── PERFORMANCE (GH axis / muscle / endurance / hormonal) ───────────────────────────────────────────
  {
    id: "ipamorelin", slug: "ipamorelin", image: "/products/ipamorelin.png", name: "Ipamorelin", mg: 5, unit: "mg",
    category: "performance", price: 39, purity: 99, featured: true,
    sequence: "Selective GH secretagogue (GHRP)", storage: STORE_COLD,
    description: "Selective, clean GH-pulse peptide — GH-axis research.",
    details: {
      overview: "A selective growth-hormone secretagogue that triggers a clean GH pulse with minimal effect on cortisol or prolactin.",
      mechanism: "Agonises the ghrelin/GHS receptor to stimulate pituitary GH release without the appetite/cortisol effects of older GHRPs.",
      suitedFor: ["performance", "recovery", "longevity", "wellness"],
      organsSystems: ["Pituitary (GH axis)", "Liver (IGF-1)", "Skeletal muscle", "Bone"],
      biomarkers: ["GH pulse amplitude", "IGF-1"],
      studies: [{ finding: "Selective GH release with low prolactin/cortisol in preclinical/early data.", evidence: "preclinical" }],
      benefits: ["Clean GH-pulse research", "Pairs with GHRH analogs"],
      sideEffects: ["Mild head-rush/flushing", "Water retention possible"],
      stacking: ["CJC-1295 No DAC", "Tesamorelin", "Sermorelin"],
    },
  },
  {
    id: "cjc-1295-no-dac", slug: "cjc-1295-no-dac", image: "/products/cjc-1295-no-dac.png", name: "CJC-1295 No DAC", mg: 5, unit: "mg",
    category: "performance", price: 42, purity: 99, featured: true,
    sequence: "GHRH analog (Mod GRF 1-29)", storage: STORE_COLD,
    description: "GHRH analog — pulsatile GH release research.",
    details: {
      overview: "A modified GHRH (1-29) analog studied for amplifying natural, pulsatile GH release; commonly paired with a GHRP.",
      mechanism: "Binds pituitary GHRH receptors to increase GH secretion in physiological pulses (no DAC = shorter, more pulsatile action).",
      suitedFor: ["performance", "recovery", "longevity"],
      organsSystems: ["Pituitary (GH axis)", "Liver (IGF-1)", "Skeletal muscle"],
      biomarkers: ["GH", "IGF-1"],
      studies: [{ finding: "GHRH analogs increase GH/IGF-1 in human studies.", evidence: "human-early" }],
      benefits: ["Synergises with GHRPs", "Physiological GH-pulse research"],
      sideEffects: ["Flushing, water retention", "Injection-site reactions"],
      stacking: ["Ipamorelin", "GHRP-2", "GHRP-6"],
    },
  },
  {
    id: "cjc-1295-dac", slug: "cjc-1295-dac", image: "/products/cjc-1295-dac.png", name: "CJC-1295 DAC", mg: 5, unit: "mg",
    category: "performance", price: 79, purity: 99,
    sequence: "GHRH analog with Drug Affinity Complex", storage: STORE_COLD,
    description: "Long-acting GHRH analog — sustained GH/IGF-1 research.",
    details: {
      overview: "A GHRH analog with a Drug Affinity Complex (DAC) that binds albumin for a long half-life and sustained GH/IGF-1 elevation.",
      mechanism: "Albumin binding extends action for days, producing a sustained 'GH bleed' rather than sharp pulses.",
      suitedFor: ["performance", "recovery", "longevity"],
      organsSystems: ["Pituitary (GH axis)", "Liver (IGF-1)", "Skeletal muscle"],
      biomarkers: ["GH", "IGF-1 (sustained elevation)"],
      studies: [{ finding: "Sustained multi-day increases in GH and IGF-1 in human study.", evidence: "human-early" }],
      benefits: ["Long-acting GH/IGF-1 elevation research"],
      sideEffects: ["Water retention, flushing", "Less physiological (non-pulsatile)"],
      stacking: ["Ipamorelin", "GHRP-2"],
    },
  },
  {
    id: "blend-cjc-ipa", slug: "cjc-1295-ipamorelin-blend", image: "/products/cjc-1295-ipamorelin-blend.png", name: "CJC-1295 + Ipamorelin Blend", mg: 10, unit: "mg",
    category: "performance", price: 79, purity: 99, featured: true,
    sequence: "GHRH analog + GHRP (5+5)", storage: STORE_COLD,
    description: "The classic GH-axis stack — GHRH + GHRP synergy.",
    details: {
      overview: "The most common GH-axis research pairing: a GHRH analog (CJC-1295 No DAC) plus a selective GHRP (Ipamorelin) for synergistic GH release.",
      mechanism: "GHRH and GHRP act on different receptors; together they produce a larger, cleaner GH pulse than either alone.",
      suitedFor: ["performance", "recovery", "longevity", "wellness"],
      organsSystems: ["Pituitary", "Liver (IGF-1)", "Skeletal muscle", "Bone"],
      biomarkers: ["GH pulse", "IGF-1"],
      studies: [{ finding: "GHRH+GHRP combinations amplify GH release in human studies.", evidence: "human-early" }],
      benefits: ["Synergistic GH-pulse research", "Convenient combined vial"],
      sideEffects: ["Flushing, water retention"],
      stacking: ["Tesamorelin"],
    },
  },
  {
    id: "ghrp-2", slug: "ghrp-2", image: "/products/ghrp-2.png", name: "GHRP-2", mg: 5, unit: "mg",
    category: "performance", price: 38, purity: 99,
    sequence: "Growth-hormone-releasing peptide-2", storage: STORE_COLD,
    description: "Potent GH secretagogue — GH-axis & appetite research.",
    details: {
      overview: "A potent growth-hormone-releasing peptide that strongly stimulates GH and modestly raises appetite.",
      mechanism: "Ghrelin-receptor agonism drives strong pituitary GH release; some prolactin/cortisol effect at higher levels.",
      suitedFor: ["performance", "recovery"],
      organsSystems: ["Pituitary", "Liver (IGF-1)", "GI (appetite)"],
      biomarkers: ["GH", "IGF-1", "Appetite/ghrelin signalling"],
      studies: [{ finding: "Strong GH release in human studies.", evidence: "human-early" }],
      benefits: ["Potent GH-pulse research"],
      sideEffects: ["Increased appetite, cortisol/prolactin rise", "Water retention"],
      stacking: ["CJC-1295 No DAC"],
    },
  },
  {
    id: "ghrp-6", slug: "ghrp-6", image: "/products/ghrp-6.png", name: "GHRP-6", mg: 5, unit: "mg",
    category: "performance", price: 38, purity: 99,
    sequence: "Growth-hormone-releasing peptide-6", storage: STORE_COLD,
    description: "GH secretagogue with marked appetite-stimulation research.",
    details: {
      overview: "An early GHRP that stimulates GH release and strongly increases appetite via ghrelin signalling.",
      mechanism: "Ghrelin-receptor agonism stimulating GH and hunger; also studied for cytoprotective effects.",
      suitedFor: ["performance", "recovery"],
      organsSystems: ["Pituitary", "Liver (IGF-1)", "GI (appetite)", "Heart (cytoprotection research)"],
      biomarkers: ["GH", "IGF-1", "Appetite"],
      studies: [{ finding: "GH release and appetite stimulation in studies; cardioprotective signals in models.", evidence: "preclinical" }],
      benefits: ["GH + appetite research", "Cytoprotection signals"],
      sideEffects: ["Strong hunger, water retention", "Cortisol/prolactin rise"],
      stacking: ["CJC-1295 No DAC"],
    },
  },
  {
    id: "hexarelin", slug: "hexarelin", image: "/products/hexarelin.png", name: "Hexarelin", mg: 5, unit: "mg",
    category: "performance", price: 49, purity: 99,
    sequence: "Hexapeptide GH secretagogue", storage: STORE_COLD,
    description: "Potent GHRP with cardiac-protection research.",
    details: {
      overview: "A potent GH secretagogue also studied for direct cardiovascular effects via CD36/ghrelin pathways.",
      mechanism: "Strong GH release plus cardiac actions independent of GH (CD36 receptor), studied for cardioprotection.",
      suitedFor: ["performance", "recovery", "cardiovascular"],
      organsSystems: ["Pituitary", "Heart (myocardium)", "Liver (IGF-1)"],
      biomarkers: ["GH", "IGF-1", "Cardiac-function indices"],
      studies: [{ finding: "Potent GH release; cardioprotective effects in models.", evidence: "preclinical" }],
      benefits: ["Potent GH + cardiac research"],
      sideEffects: ["Desensitisation with prolonged use", "Cortisol/prolactin rise"],
      stacking: ["CJC-1295 No DAC"],
    },
  },
  {
    id: "sermorelin", slug: "sermorelin", image: "/products/sermorelin.png", name: "Sermorelin", mg: 5, unit: "mg",
    category: "performance", price: 49, purity: 99,
    sequence: "GHRH (1-29) analog", storage: STORE_COLD,
    description: "GHRH (1-29) — physiological GH-axis research.",
    details: {
      overview: "A GHRH (1-29) analog (formerly used clinically to test/stimulate GH) studied for physiological GH support.",
      mechanism: "Stimulates pituitary GHRH receptors to release GH in a natural, feedback-regulated pulse.",
      suitedFor: ["performance", "longevity", "recovery", "wellness"],
      organsSystems: ["Pituitary", "Liver (IGF-1)", "Skeletal muscle"],
      biomarkers: ["GH", "IGF-1"],
      studies: [{ finding: "Raised GH/IGF-1 and used as a diagnostic GH stimulant in humans.", evidence: "approved" }],
      benefits: ["Physiological GH-axis research"],
      sideEffects: ["Flushing, injection-site reactions"],
      stacking: ["Ipamorelin", "GHRP-2"],
    },
  },
  {
    id: "hgh-191aa", slug: "hgh-191aa", image: "/products/hgh-191aa.png", name: "HGH 191AA (Somatropin)", mg: 10, unit: "iu",
    category: "performance", price: 89, purity: 97,
    sequence: "Recombinant 191-aa human growth hormone", storage: STORE_COLD,
    description: "Recombinant growth hormone — GH/IGF-1 reference (prescription drug).",
    details: {
      overview: "Recombinant 191-amino-acid human growth hormone (somatropin), a prescription medicine, used as a research reference for the GH/IGF-1 axis.",
      mechanism: "Directly activates GH receptors, driving IGF-1 production, protein synthesis, lipolysis and growth signalling.",
      suitedFor: ["performance", "recovery", "longevity", "metabolic"],
      organsSystems: ["Liver (IGF-1)", "Skeletal muscle", "Bone", "Adipose tissue"],
      biomarkers: ["IGF-1", "Fasting glucose/insulin", "Body composition"],
      studies: [{ finding: "Established effects on growth, body composition and IGF-1 in clinical use.", evidence: "approved" }],
      benefits: ["Direct GH/IGF-1 research reference"],
      sideEffects: ["Fluid retention, joint pain, carpal tunnel", "Insulin resistance/hyperglycaemia", "Prescription-only medicine"],
      stacking: ["IGF-1 LR3"],
    },
  },
  {
    id: "igf-1-lr3", slug: "igf-1-lr3", image: "/products/igf-1-lr3.png", name: "IGF-1 LR3", mg: 1, unit: "mg",
    category: "performance", price: 119, purity: 98,
    sequence: "Long R3 insulin-like growth factor-1", storage: STORE_COLD,
    description: "Long-acting IGF-1 analog — anabolic & growth research.",
    details: {
      overview: "A long-acting analog of insulin-like growth factor-1 with reduced binding-protein affinity, giving extended activity.",
      mechanism: "Activates IGF-1 receptors to drive cell proliferation, protein synthesis, satellite-cell activation and hypertrophy.",
      suitedFor: ["performance", "recovery"],
      organsSystems: ["Skeletal muscle", "Liver", "Connective tissue"],
      biomarkers: ["IGF-1 signalling", "Muscle protein synthesis", "Blood glucose"],
      studies: [{ finding: "Potent anabolic/proliferative effects in cell and animal models.", evidence: "preclinical" }],
      benefits: ["Anabolic/growth-pathway research"],
      sideEffects: ["Hypoglycaemia risk", "Theoretical proliferative risks — research only"],
      stacking: ["HGH 191AA", "MGF"],
    },
  },
  {
    id: "mgf", slug: "mgf", image: "/products/mgf.png", name: "MGF (Mechano Growth Factor)", mg: 5, unit: "mg",
    category: "performance", price: 59, purity: 98,
    sequence: "IGF-1Ec splice variant", storage: STORE_COLD,
    description: "Muscle-repair IGF-1 splice variant — satellite-cell research.",
    details: {
      overview: "A splice variant of IGF-1 (IGF-1Ec) released by mechanically stressed muscle, studied for satellite-cell activation and repair.",
      mechanism: "Activates and proliferates muscle satellite (stem) cells to initiate repair and hypertrophy after mechanical load.",
      suitedFor: ["performance", "recovery"],
      organsSystems: ["Skeletal muscle (satellite cells)", "Heart (repair research)"],
      biomarkers: ["Satellite-cell activation", "Muscle repair markers"],
      studies: [{ finding: "Promoted muscle-cell proliferation and repair in models.", evidence: "preclinical" }],
      benefits: ["Muscle-repair / satellite-cell research"],
      sideEffects: ["Limited human safety data"],
      stacking: ["PEG-MGF", "IGF-1 LR3"],
    },
  },
  {
    id: "peg-mgf", slug: "peg-mgf", image: "/products/peg-mgf.png", name: "PEG-MGF", mg: 5, unit: "mg",
    category: "performance", price: 65, purity: 98,
    sequence: "PEGylated mechano growth factor", storage: STORE_COLD,
    description: "Long-acting MGF — extended muscle-repair research.",
    details: {
      overview: "A PEGylated, longer-acting form of MGF studied for sustained satellite-cell and muscle-repair signalling.",
      mechanism: "PEGylation extends half-life so MGF's satellite-cell activation persists systemically rather than locally.",
      suitedFor: ["performance", "recovery"],
      organsSystems: ["Skeletal muscle", "Heart"],
      biomarkers: ["Satellite-cell activation", "Muscle repair markers"],
      studies: [{ finding: "Extended muscle-repair signalling vs native MGF in models.", evidence: "preclinical" }],
      benefits: ["Sustained muscle-repair research"],
      sideEffects: ["Limited human safety data"],
      stacking: ["MGF", "IGF-1 LR3"],
    },
  },
  {
    id: "follistatin-344", slug: "follistatin-344", image: "/products/follistatin-344.png", name: "Follistatin 344", mg: 1, unit: "mg",
    category: "performance", price: 199, purity: 98,
    sequence: "Myostatin-binding glycoprotein", storage: STORE_COLD,
    description: "Myostatin inhibitor — muscle-growth research.",
    details: {
      overview: "A glycoprotein that binds and inhibits myostatin and related TGF-β ligands, studied for muscle growth.",
      mechanism: "Sequesters myostatin (a negative regulator of muscle), removing the brake on muscle-fibre growth.",
      suitedFor: ["performance", "recovery"],
      organsSystems: ["Skeletal muscle", "Ovary/reproductive (native role)"],
      biomarkers: ["Myostatin levels", "Lean mass", "Muscle-fibre size"],
      studies: [{ finding: "Marked muscle hypertrophy with follistatin/myostatin inhibition in animal models.", evidence: "preclinical" }],
      benefits: ["Myostatin-inhibition / hypertrophy research"],
      sideEffects: ["Limited human safety data; systemic TGF-β effects unknown"],
      stacking: ["Ace-031", "IGF-1 LR3"],
    },
  },
  {
    id: "ace-031", slug: "ace-031", image: "/products/ace-031.png", name: "ACE-031 (ActRIIB)", mg: 1, unit: "mg",
    category: "performance", price: 219, purity: 98,
    sequence: "Soluble activin receptor IIB", storage: STORE_COLD,
    description: "Activin-receptor decoy — muscle-mass research.",
    details: {
      overview: "A soluble decoy of the activin type-IIB receptor studied for increasing muscle mass by blocking myostatin/activin signalling.",
      mechanism: "Acts as a 'ligand trap' for myostatin and activins, preventing them from signalling muscle-growth inhibition.",
      suitedFor: ["performance"],
      organsSystems: ["Skeletal muscle", "Bone (density research)"],
      biomarkers: ["Lean mass", "Muscle volume", "Bone density"],
      studies: [{ finding: "Increased muscle mass in trials; development paused over vascular side effects.", evidence: "clinical" }],
      benefits: ["Muscle-mass / myostatin-pathway research"],
      sideEffects: ["Reported nosebleeds/gum bleeding, telangiectasia in trials — research only"],
      stacking: ["Follistatin 344"],
    },
  },
  {
    id: "aicar", slug: "aicar", image: "/products/aicar.png", name: "AICAR", mg: 50, unit: "mg",
    category: "performance", price: 71, purity: 99,
    sequence: "AMPK activator (AICA riboside)", storage: STORE_COLD,
    description: "AMPK activator — endurance & metabolic 'exercise-mimetic' research.",
    details: {
      overview: "An AMP-analog that activates AMPK, studied as an 'exercise mimetic' for endurance and metabolic adaptation.",
      mechanism: "Activates AMPK, shifting cells toward fat oxidation, mitochondrial biogenesis and glucose uptake — mimicking exercise signalling.",
      suitedFor: ["performance", "metabolic", "weight-management"],
      organsSystems: ["Skeletal muscle", "Liver", "Mitochondria"],
      biomarkers: ["AMPK activity", "Endurance capacity", "Glucose uptake"],
      studies: [{ finding: "Increased endurance and mitochondrial biogenesis in rodent models.", evidence: "preclinical" }],
      benefits: ["Endurance / metabolic-adaptation research"],
      sideEffects: ["Limited human safety data; banned in sport (WADA)"],
      stacking: ["MOTS-C", "NAD+"],
    },
  },
  {
    id: "mots-c", slug: "mots-c", image: "/products/mots-c.png", name: "MOTS-c", mg: 10, unit: "mg",
    category: "performance", price: 79, purity: 99,
    sequence: "Mitochondrial-derived peptide (16-aa)", storage: STORE_COLD,
    description: "Mitochondrial peptide — metabolism, endurance & longevity research.",
    details: {
      overview: "A mitochondrial-derived peptide studied for metabolic regulation, exercise capacity and healthy aging.",
      mechanism: "Activates AMPK and influences nuclear gene expression under metabolic stress, improving glucose handling and mitochondrial function.",
      suitedFor: ["performance", "metabolic", "longevity", "weight-management"],
      organsSystems: ["Skeletal muscle", "Mitochondria (systemic)", "Liver", "Adipose tissue"],
      biomarkers: ["AMPK activity", "Insulin sensitivity", "Exercise capacity"],
      studies: [{ finding: "Improved metabolic flexibility, insulin sensitivity and exercise capacity in animal models.", evidence: "preclinical" }],
      benefits: ["Metabolic & endurance research", "Mitochondrial-aging research"],
      sideEffects: ["Limited human safety data"],
      stacking: ["NAD+", "5-Amino-1MQ", "SS-31"],
    },
  },
  {
    id: "gdf-8", slug: "gdf-8", image: "/products/gdf-8.png", name: "GDF-8 (Myostatin)", mg: 1, unit: "mg",
    category: "performance", price: 149, purity: 98,
    sequence: "Growth differentiation factor 8", storage: STORE_COLD,
    description: "Myostatin reference protein — muscle-regulation research.",
    details: {
      overview: "Growth differentiation factor-8 (myostatin) itself — the negative regulator of muscle growth, supplied as a research reference protein.",
      mechanism: "Signals through ActRIIB to limit muscle-fibre growth; used to study myostatin pathways and inhibitors.",
      suitedFor: ["performance"],
      organsSystems: ["Skeletal muscle"],
      biomarkers: ["Myostatin signalling", "Muscle-fibre size"],
      studies: [{ finding: "Myostatin loss-of-function causes muscle overgrowth across species.", evidence: "preclinical" }],
      benefits: ["Myostatin-pathway research reference"],
      sideEffects: ["Research reference protein only"],
      stacking: ["Follistatin 344", "Ace-031"],
    },
  },
 
  // ─────────────────────────────────────────── COGNITIVE & MOOD (incl. sleep / libido / hormonal-CNS) ───────────────────────────────────────────
  {
    id: "semax", slug: "semax", image: "/products/semax.png", name: "Semax", mg: 10, unit: "mg",
    category: "cognitive", price: 55, purity: 99, featured: true,
    sequence: "ACTH(4-10) heptapeptide analog", storage: STORE_COLD,
    description: "Nootropic heptapeptide — BDNF & neuroprotection research.",
    details: {
      overview: "A synthetic ACTH(4-10) fragment analog (used in Russia clinically) studied for cognition, focus and neuroprotection.",
      mechanism: "Raises BDNF/NGF, modulates dopaminergic and serotonergic systems, and shows neuroprotective effects in ischaemia.",
      suitedFor: ["cognitive", "wellness", "health"],
      organsSystems: ["Brain (hippocampus, cortex)", "Nervous system"],
      biomarkers: ["BDNF", "NGF", "Cognitive/attention scores"],
      studies: [
        { finding: "Raised BDNF and improved cognition/recovery in stroke and cognitive studies.", evidence: "human-early" },
      ],
      benefits: ["Focus / memory research", "Neuroprotection (stroke) research"],
      sideEffects: ["Generally well tolerated; intranasal route common"],
      stacking: ["Selank"],
    },
  },
  {
    id: "selank", slug: "selank", image: "/products/selank.png", name: "Selank", mg: 10, unit: "mg",
    category: "cognitive", price: 52, purity: 99, featured: true,
    sequence: "Tuftsin-derived heptapeptide", storage: STORE_COLD,
    description: "Anxiolytic peptide — calm, focus & immune research.",
    details: {
      overview: "A tuftsin-derived peptide studied for anti-anxiety effects without sedation or dependence.",
      mechanism: "Modulates GABA/serotonin systems and raises BDNF; also stabilises enkephalins and modulates immune signalling.",
      suitedFor: ["cognitive", "wellness", "immunity"],
      organsSystems: ["Brain (limbic system)", "Immune system"],
      biomarkers: ["BDNF", "Anxiety scores", "Cytokine balance (IL-6)"],
      studies: [{ finding: "Reduced anxiety and improved cognition in early human/animal studies.", evidence: "human-early" }],
      benefits: ["Anxiolytic / calm-focus research", "Non-sedating in studies"],
      sideEffects: ["Generally well tolerated; intranasal route common"],
      stacking: ["Semax"],
    },
  },
  {
    id: "dsip", slug: "dsip", image: "/products/dsip.png", name: "DSIP", mg: 5, unit: "mg",
    category: "cognitive", price: 49, purity: 98,
    sequence: "Delta sleep-inducing peptide", storage: STORE_COLD,
    description: "Sleep-modulating peptide — sleep & stress research.",
    details: {
      overview: "A naturally occurring nonapeptide studied for promoting delta-wave (deep) sleep and stress resilience.",
      mechanism: "Modulates sleep architecture and stress hormones; precise receptor mechanism remains under study.",
      suitedFor: ["sleep", "cognitive", "wellness"],
      organsSystems: ["Brain (sleep centres)", "HPA axis"],
      biomarkers: ["Sleep-stage architecture (delta)", "Cortisol"],
      studies: [{ finding: "Improved sleep measures and stress resilience in early studies.", evidence: "human-early" }],
      benefits: ["Deep-sleep research", "Stress-modulation research"],
      sideEffects: ["Limited human safety data"],
      stacking: ["Melatonin", "Epithalon"],
    },
  },
  {
    id: "melatonin", slug: "melatonin", image: "/products/melatonin.png", name: "Melatonin", mg: 10, unit: "mg",
    category: "cognitive", price: 29, purity: 99,
    sequence: "Pineal hormone (indoleamine)", storage: STORE_COLD,
    description: "Circadian hormone — sleep, antioxidant & longevity research.",
    details: {
      overview: "The pineal hormone governing circadian rhythm, widely studied for sleep, antioxidant defence and aging.",
      mechanism: "Activates MT1/MT2 receptors to set the sleep–wake clock; also a direct free-radical scavenger.",
      suitedFor: ["sleep", "longevity", "wellness", "cognitive"],
      organsSystems: ["Brain (SCN/pineal)", "Eye", "Immune system", "Mitochondria"],
      biomarkers: ["Melatonin rhythm", "Sleep latency/quality", "Oxidative-stress markers"],
      studies: [{ finding: "Improves sleep onset and circadian alignment in clinical use.", evidence: "clinical" }],
      benefits: ["Sleep & circadian research", "Antioxidant research"],
      sideEffects: ["Drowsiness, vivid dreams", "Generally well tolerated"],
      stacking: ["DSIP", "Epithalon"],
    },
  },
  {
    id: "oxytocin", slug: "oxytocin", image: "/products/oxytocin.png", name: "Oxytocin Acetate", mg: 2, unit: "mg",
    category: "cognitive", price: 45, purity: 99,
    sequence: "Nonapeptide hormone", storage: STORE_COLD,
    description: "Social/bonding hormone — mood & behaviour research.",
    details: {
      overview: "The 'bonding' nonapeptide hormone studied for social behaviour, mood and stress in neuroscience research.",
      mechanism: "Activates oxytocin receptors in limbic and social-cognition circuits; also drives uterine/lactation physiology.",
      suitedFor: ["cognitive", "wellness", "sexual-health"],
      organsSystems: ["Brain (limbic/social circuits)", "Uterus", "Mammary tissue"],
      biomarkers: ["Cortisol/stress response", "Social-behaviour measures"],
      studies: [{ finding: "Intranasal oxytocin altered social cognition and stress markers in human studies.", evidence: "human-early" }],
      benefits: ["Social-cognition / mood research"],
      sideEffects: ["Generally well tolerated intranasally; cardiovascular effects with IV dosing"],
      stacking: [],
    },
  },
  {
    id: "pt-141", slug: "pt-141", image: "/products/pt-141.png", name: "PT-141 (Bremelanotide)", mg: 10, unit: "mg",
    category: "cognitive", price: 59, purity: 99,
    sequence: "Melanocortin receptor agonist", storage: STORE_COLD,
    description: "Melanocortin agonist — libido & arousal research (approved drug).",
    details: {
      overview: "A melanocortin-receptor agonist (approved as Vyleesi for low sexual desire) studied for libido and arousal via central pathways.",
      mechanism: "Activates central MC4 receptors influencing sexual-desire pathways — acting on the brain rather than vasculature.",
      suitedFor: ["sexual-health", "cognitive"],
      organsSystems: ["Brain (melanocortin/MC4 circuits)"],
      biomarkers: ["Arousal/desire scores"],
      studies: [{ finding: "Improved sexual desire/arousal measures in clinical trials.", evidence: "approved" }],
      benefits: ["Central libido/arousal research"],
      sideEffects: ["Nausea, flushing", "Transient blood-pressure rise", "Possible skin darkening"],
      stacking: ["Melanotan 2"],
    },
  },
  {
    id: "kisspeptin-10", slug: "kisspeptin-10", image: "/products/kisspeptin-10.png", name: "Kisspeptin-10", mg: 5, unit: "mg",
    category: "cognitive", price: 69, purity: 99,
    sequence: "KISS1 decapeptide fragment", storage: STORE_COLD,
    description: "Reproductive-axis trigger — hormonal & arousal research.",
    details: {
      overview: "A fragment of the KISS1 gene product that sits at the top of the reproductive hormone axis, studied for fertility and libido.",
      mechanism: "Stimulates hypothalamic GnRH release, raising LH/FSH and downstream sex hormones; also influences arousal pathways.",
      suitedFor: ["sexual-health", "performance", "wellness"],
      organsSystems: ["Hypothalamus (GnRH neurons)", "Pituitary (LH/FSH)", "Gonads"],
      biomarkers: ["LH/FSH", "Testosterone/estradiol", "Arousal measures"],
      studies: [{ finding: "Raised LH and sex hormones; modulated arousal in human studies.", evidence: "human-early" }],
      benefits: ["Reproductive-axis research", "Libido research"],
      sideEffects: ["Generally well tolerated in trials"],
      stacking: ["Gonadorelin"],
    },
  },
 
  // Hormonal / reproductive (placed in performance for the endocrine ones, cognitive for CNS ones above)
  {
    id: "hcg", slug: "hcg", image: "/products/hcg.png", name: "HCG", mg: 5000, unit: "iu",
    category: "performance", price: 65, purity: 99,
    sequence: "Human chorionic gonadotropin", storage: STORE_COLD,
    description: "LH-mimetic gonadotropin — gonadal-axis research (prescription drug).",
    details: {
      overview: "Human chorionic gonadotropin, a prescription hormone that mimics LH, studied for gonadal stimulation and fertility.",
      mechanism: "Activates LH receptors on the gonads to stimulate testosterone (testes) or ovulation/progesterone (ovaries).",
      suitedFor: ["performance", "sexual-health", "health"],
      organsSystems: ["Testes/ovaries", "Pituitary–gonadal axis"],
      biomarkers: ["Testosterone", "Estradiol/progesterone", "Sperm/ovulation markers"],
      studies: [{ finding: "Established gonadotropic effects in clinical fertility/endocrine use.", evidence: "approved" }],
      benefits: ["Gonadal-axis research reference"],
      sideEffects: ["Gynaecomastia, fluid retention", "OHSS risk (females)", "Prescription-only medicine"],
      stacking: ["HMG", "Gonadorelin"],
    },
  },
  {
    id: "hmg", slug: "hmg", image: "/products/hmg.png", name: "HMG (Menotropin)", mg: 75, unit: "iu",
    category: "performance", price: 79, purity: 99,
    sequence: "FSH + LH gonadotropin mix", storage: STORE_COLD,
    description: "FSH/LH gonadotropin — fertility-axis research (prescription drug).",
    details: {
      overview: "Human menopausal gonadotropin (FSH+LH activity), a prescription fertility hormone studied for gametogenesis.",
      mechanism: "Provides FSH and LH activity to stimulate follicle development/spermatogenesis and sex-hormone production.",
      suitedFor: ["performance", "health", "sexual-health"],
      organsSystems: ["Ovaries/testes", "Pituitary–gonadal axis"],
      biomarkers: ["FSH/LH", "Estradiol/testosterone", "Follicle/sperm counts"],
      studies: [{ finding: "Established use in assisted reproduction.", evidence: "approved" }],
      benefits: ["Gametogenesis / fertility research"],
      sideEffects: ["OHSS, multiple follicles", "Prescription-only medicine"],
      stacking: ["HCG"],
    },
  },
  {
    id: "gonadorelin", slug: "gonadorelin", image: "/products/gonadorelin.png", name: "Gonadorelin", mg: 2, unit: "mg",
    category: "performance", price: 45, purity: 99,
    sequence: "GnRH decapeptide", storage: STORE_COLD,
    description: "GnRH — pituitary–gonadal axis research.",
    details: {
      overview: "Synthetic gonadotropin-releasing hormone studied for stimulating the pituitary–gonadal axis.",
      mechanism: "Pulsatile GnRH stimulates pituitary LH/FSH release; continuous exposure instead down-regulates the axis.",
      suitedFor: ["performance", "health", "sexual-health"],
      organsSystems: ["Pituitary (gonadotropes)", "Gonads"],
      biomarkers: ["LH/FSH", "Testosterone/estradiol"],
      studies: [{ finding: "Diagnostic and therapeutic gonadotropic effects established clinically.", evidence: "approved" }],
      benefits: ["HPG-axis research"],
      sideEffects: ["Headache, flushing", "Axis suppression with continuous use"],
      stacking: ["HCG", "Kisspeptin-10"],
    },
  },
  {
    id: "melanotan-2", slug: "melanotan-2", image: "/products/melanotan-2.png", name: "Melanotan 2", mg: 10, unit: "mg",
    category: "longevity", price: 49, purity: 99,
    sequence: "α-MSH analog (melanocortin agonist)", storage: STORE_COLD,
    description: "Melanocortin agonist — pigmentation & libido research.",
    details: {
      overview: "A non-selective melanocortin agonist studied for skin pigmentation (tanning) and, via MC4, libido.",
      mechanism: "Activates MC1 receptors (melanin/tanning) and MC4 receptors (appetite/libido).",
      suitedFor: ["skin", "sexual-health"],
      organsSystems: ["Skin (melanocytes)", "Brain (MC4 circuits)"],
      biomarkers: ["Melanin density", "Arousal/appetite measures"],
      studies: [{ finding: "Increased melanogenesis and libido effects in studies.", evidence: "human-early" }],
      benefits: ["Pigmentation/photoprotection research", "Libido research"],
      sideEffects: ["Nausea, flushing, darkening of moles", "Appetite suppression"],
      stacking: ["PT-141", "Melanotan 1"],
    },
  },
  {
    id: "melanotan-1", slug: "melanotan-1", image: "/products/melanotan-1.png", name: "Melanotan 1 (Afamelanotide)", mg: 10, unit: "mg",
    category: "longevity", price: 55, purity: 99,
    sequence: "α-MSH analog (MC1-selective)", storage: STORE_COLD,
    description: "MC1-selective melanocortin — photoprotection research (approved in EPP).",
    details: {
      overview: "A more MC1-selective α-MSH analog (clinically approved as afamelanotide for erythropoietic protoporphyria) studied for pigmentation and photoprotection.",
      mechanism: "Selective MC1-receptor activation increases eumelanin, providing UV/photoprotection with fewer MC4 (libido/appetite) effects than MT-2.",
      suitedFor: ["skin", "health"],
      organsSystems: ["Skin (melanocytes)"],
      biomarkers: ["Melanin density", "Photoprotection/UV tolerance"],
      studies: [{ finding: "Increased pain-free light exposure in EPP clinical trials.", evidence: "approved" }],
      benefits: ["Photoprotection / pigmentation research"],
      sideEffects: ["Nausea, skin darkening; injection-site reactions"],
      stacking: ["Melanotan 2"],
    },
  },
  {
    id: "pnc-27", slug: "pnc-27", image: "/products/pnc-27.png", name: "PNC-27", mg: 5, unit: "mg",
    category: "longevity", price: 119, purity: 98,
    sequence: "p53-derived membrane-disrupting peptide", storage: STORE_COLD,
    description: "Anticancer research peptide — selective tumour-cell studies.",
    details: {
      overview: "A p53-derived peptide studied for selectively disrupting cancer-cell membranes while sparing normal cells.",
      mechanism: "Binds HDM-2 expressed on cancer-cell membranes, forming pores that cause selective necrosis of tumour cells in vitro.",
      suitedFor: ["longevity", "health"],
      organsSystems: ["Studied across multiple tumour-cell lines (in vitro)"],
      biomarkers: ["Cancer-cell viability/necrosis (in vitro)"],
      studies: [{ finding: "Selective killing of cancer cell lines without harming normal cells in vitro.", evidence: "invitro" }],
      benefits: ["Oncology / membrane-targeting research"],
      sideEffects: ["No human safety data — strictly in-vitro research"],
      stacking: [],
    },
  },
 
  // ─────────────────────────────────────────── ACCESSORIES ───────────────────────────────────────────
  {
    id: "bac-water", slug: "bacteriostatic-water", image: "/products/bacteriostatic-water.png", name: "Bacteriostatic Water", mg: null,
    category: "accessories", price: 12, purity: 100,
    storage: "Store at room temperature, away from light.",
    description: "Sterile bacteriostatic water for reconstitution.",
    details: {
      overview: "Sterile water containing 0.9% benzyl alcohol as a bacteriostatic agent, used to reconstitute lyophilised research peptides.",
      mechanism: "The benzyl alcohol inhibits bacterial growth, allowing multi-use reconstitution over a typical 28-day window.",
      suitedFor: ["wellness"],
      organsSystems: [],
      biomarkers: [],
      studies: [],
      benefits: ["Reconstitution diluent for lyophilised peptides", "Bacteriostatic for multi-use vials"],
      sideEffects: ["Not for use in neonates; standard handling precautions"],
      stacking: [],
    },
  },
];
 
// Bundles (research stacks) — extend as needed
export type Bundle = {
  id: string; slug: string; name: string; productIds: string[]; price: number; original: number; tag: string;
};
export const BUNDLES: Bundle[] = [
  { id: "b1", slug: "recovery-stack", name: "Recovery Stack", productIds: ["bpc-157", "tb-500"], price: 95, original: 108, tag: "Save $13" },
  { id: "b2", slug: "gh-axis-stack", name: "GH-Axis Stack", productIds: ["cjc-1295-no-dac", "ipamorelin"], price: 72, original: 81, tag: "Save $9" },
  { id: "b3", slug: "longevity-stack", name: "Longevity Stack", productIds: ["epithalon", "ghk-cu", "nad-plus"], price: 175, original: 199, tag: "Save $24" },
  { id: "b4", slug: "metabolic-stack", name: "Metabolic Stack", productIds: ["tirzepatide", "cagrilintide"], price: 269, original: 288, tag: "Save $19" },
];
 
export const getProduct = (slug: string) => PRODUCTS.find((p) => p.slug === slug);
export const getById = (id: string) => PRODUCTS.find((p) => p.id === id);
export const byCategory = (c: Category) => PRODUCTS.filter((p) => p.category === c);
export const FREE_SHIP_THRESHOLD = 150;
 
